using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Reliable_Reservations.Models.DTOs.TimeSlot
{
    public class TimeSlotUpdateDto
    {
        [Required]
        public DateTime StartTime { get; set; }

        [Required]
        public DateTime EndTime { get; set; }

        [JsonIgnore]
        public int SlotDuration { get; set; } = 90; // If changed, don't forget to update TimeSlotAutoGenerateDto!
    }
}
