using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Reliable_Reservations.Models.DTOs.TimeSlot
{
    public class TimeSlotAutoGenerateDto
    {
        [Required(ErrorMessage = "Start date is required.")]
        public DateTime StartDate { get; set; }

        [Required(ErrorMessage = "End date is required.")]
        public DateTime EndDate { get; set; }

        [JsonIgnore]
        public int SlotDuration { get; set; } = 90; // If changed, don't forget to update TimeSlotUpdateDto!
    }
}