using Reliable_Reservations.Models;
using Reliable_Reservations.Models.DTOs;

namespace Reliable_Reservations.Services.IServices
{
    public interface ITimeSlotService
    {
        Task<TimeSlotDto> GetTimeSlotByIdAsync(int id);
        Task<IEnumerable<TimeSlotDto>> GetAllTimeSlotsAsync();
        Task<TimeSlot?> GetExistingTimeSlotAsync(DateTime startTime, DateTime endTime);
        Task<TimeSlotDto> CreateTimeSlotAsync(TimeSlotCreateDto timeSlotCreateDto);
        Task<IEnumerable<TimeSlotDto>> AutoGenerateTimeSlots(TimeSlotAutoGenerateDto timeSlotAutoGenerateDto);
        Task UpdateTimeSlotAsync(int id, TimeSlotUpdateDto timeSlotCreateDto);
        Task DeleteTimeSlotAsync(int id);
    }
}
